### ISSUE TITLE
How to run API server with https?

### ISSUE THREAD

**Issue by SharifTanvir** [KlausSchaefers/qux-java#4]
while I am passing the request through API I am getting this-

`Mixed Content: The page at 'https://prototype.tikweb.com/#/' was loaded over HTTPS, but requested an insecure resource 'http://api.prototype.tikweb.com:8080/rest/login/'. This request has been blocked; the content must be served over HTTPS`

I am getting my server status on http://api.prototype.tikweb.com/rest/status.json. 
But I need it on https://api.prototype.tikweb.com/rest/status.json. 

Can you give me any idea?

**Comment by KlausSchaefers** [comment]
Hi,

I put everything behind an NGINX server. This was for my the easiest as this works nice with certbot. If this is not an option, one can also configure Vertx to support ssl.

https://vertx.io/docs/vertx-core/java/#_writing_http_servers_and_clients

Quant-UX uses still vertex 3.x but the configuration should be similar.  You would have to change the start() with in https://github.com/KlausSchaefers/qux-java/blob/master/src/main/java/com/qux/MATC.java

**Comment by SharifTanvir** [comment]
Sorry, i missed your last comment. 
I have solved the issue. Thank you for your support.
